### ISSUE TITLE
IdeaBase space photos

### ISSUE THREAD

**Issue by chrisuhler** [ideabase/ideabaseweb#6]
Add photos of IdeaBase space/environment to:
- Work for IdeaBase (shows prospective employees working environment)

- How much does it cost? ( shows prospective clients our bomb ass office)

Allows for clients and students to learn more about out space without adding a new page of content.

**Comment by challahan** [comment]
Working on developing photo treatment.  Will put information about the space (and perhaps more photos) on the new About page - accessible from the footer.  Will also link the words "fabulous office space" to this page.
