### ISSUE TITLE
Powered by Students Needs Quantifier 

### ISSUE THREAD

**Issue by chrisuhler** [ideabase/ideabaseweb#7]
Powered by KSU students. some kind of qualifier. (all students?) no monitoring by staff?
Best of the best, reason you want these students vs any students. Validating the fact they are not kids practicing.

Hand Picked (Selected)

**Comment by challahan** [comment]
Believe this should be addressed in the new section added to home page - talks about only the "best" students and is also mentioned on the people page in the introduction.
